[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
